
package com.lib.apicommondemo.webservises;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Customers", targetNamespace = "http://WebServises.apicommondemo.lib.com/", wsdlLocation = "http://localhost:8888/Customers?wsdl")
public class Customers_Service
    extends Service
{

    private final static URL CUSTOMERS_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERS_EXCEPTION;
    private final static QName CUSTOMERS_QNAME = new QName("http://WebServises.apicommondemo.lib.com/", "Customers");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/Customers?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERS_WSDL_LOCATION = url;
        CUSTOMERS_EXCEPTION = e;
    }

    public Customers_Service() {
        super(__getWsdlLocation(), CUSTOMERS_QNAME);
    }

    public Customers_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERS_QNAME, features);
    }

    public Customers_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERS_QNAME);
    }

    public Customers_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERS_QNAME, features);
    }

    public Customers_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Customers_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapJavaxRs
     */
    @WebEndpoint(name = "SoapJavaxRsPort")
    public SoapJavaxRs getSoapJavaxRsPort() {
        return super.getPort(new QName("http://WebServises.apicommondemo.lib.com/", "SoapJavaxRsPort"), SoapJavaxRs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapJavaxRs
     */
    @WebEndpoint(name = "SoapJavaxRsPort")
    public SoapJavaxRs getSoapJavaxRsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WebServises.apicommondemo.lib.com/", "SoapJavaxRsPort"), SoapJavaxRs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERS_EXCEPTION!= null) {
            throw CUSTOMERS_EXCEPTION;
        }
        return CUSTOMERS_WSDL_LOCATION;
    }

}
